### ISSUE TITLE
Need to be updated to work with python 3.8

### ISSUE THREAD

**Issue by NofelYaseen** [p4lang/PI#599]
I am following the README here: https://github.com/p4lang/PI/tree/main/proto/ptf

I get the error

```
======================================================================
ERROR: l3_host_fwd.FwdTest
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vagrant/PI/proto/ptf/base_test.py", line 668, in handle
    return f(*args, **kwargs)
  File "/home/vagrant/PI/proto/ptf/l3_host_fwd/test/l3_host_fwd.py", line 43, in runTest
    eg_port_str = stringify(eg_port, 2)
  File "/home/vagrant/PI/proto/ptf/base_test.py", line 69, in stringify
    decoded_s = s.decode("hex")
AttributeError: 'str' object has no attribute 'decode'
```

I am using the vm in 
https://github.com/p4lang/tutorials/tree/master/vm-ubuntu-20.04 

The vm uses python version 3.8. I am not sure which is expected for it work?

**Comment by antoninbas** [comment]
I don't know where this code comes from, but it doesn't seem to be from this repo:
```py
decoded_s = s.decode("hex")
```

The code is as follows: 
https://github.com/p4lang/PI/blob/5a4c56ea036edce96deb32ebdd2531482aadcd07/proto/ptf/base_test.py#L66-L68

However, this code is indeed invalid in Python3.
If someone wants to update the code and validate it with a recent version of Python, a PR would be very welcome.

**Comment by rst0git** [comment]
I have opened a pull request to update the code (https://github.com/p4lang/PI/pull/600). The update is straightforward because `stringify()` implements the equivalent functionality of `int.to_bytes` in Python 3.
